// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0TSLuqeHERA6W23nrmtOmwzWZlxo4x1I',
    appId: '1:911695745598:web:a54ad61daff8ec71f2b76f',
    messagingSenderId: '911695745598',
    projectId: 'portfolio-7fdab',
    authDomain: 'portfolio-7fdab.firebaseapp.com',
    storageBucket: 'portfolio-7fdab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaqa2LrAGD8kwFOSTnV_oH6Hc3oq0rv9E',
    appId: '1:911695745598:android:1ebd672f6d7c6864f2b76f',
    messagingSenderId: '911695745598',
    projectId: 'portfolio-7fdab',
    storageBucket: 'portfolio-7fdab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy4DnojiiYuwBI_yAk06jIpBzaTy05RBE',
    appId: '1:911695745598:ios:a9e6fc5eb64ee7c7f2b76f',
    messagingSenderId: '911695745598',
    projectId: 'portfolio-7fdab',
    storageBucket: 'portfolio-7fdab.appspot.com',
    iosClientId:
        '911695745598-pjg4bkln7h867c92foa8fu9i43mpk4jd.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy4DnojiiYuwBI_yAk06jIpBzaTy05RBE',
    appId: '1:911695745598:ios:a9e6fc5eb64ee7c7f2b76f',
    messagingSenderId: '911695745598',
    projectId: 'portfolio-7fdab',
    storageBucket: 'portfolio-7fdab.appspot.com',
    iosClientId:
        '911695745598-pjg4bkln7h867c92foa8fu9i43mpk4jd.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPortfolio',
  );
}
